[project]
name = "fastmcp-descope"
version = "0.1.0"
description = "FastMCP server with Descope OAuth example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.3.4",
    "llama-stack-client>=0.2.6",
    "descope>=0.1.0",
]
