# fly.toml app configuration file generated for remote-mcp-server-fly-10xcrm on 2025-06-13T13:20:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'remote-mcp-server-fly-10xcrm'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
